### ISSUE TITLE
Oxmysql export execute

### ISSUE THREAD

**Issue by Ralle9901** [NicoDK6400/QBCore--Oversat-til-dansk#7]
SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export execute in resource oxmysql

**Comment by ningaard** [comment]
> SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export execute in resource oxmysql
Du kan få hjælp på Discorden. 😄
